name: Firebase Hosting Deploy

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build React
      run: npm install
           npm run build
    - name: Deploy to Firebase Hosting
      run: sudo npm install -g firebase-tools
           firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
